#!/usr/bin/perl
#
# dif  (should be executable)
#
# PURPOSE: Difference from $refdir/file
#
# USAGE:  dif  filename
# SAMPLE: dif  align-regroup.spi

$file = $ARGV[0];

$refdir = "/usr8/spider/docs/techs/recon1a/Procs";

system( "diff $file $refdir/$file");
