#! /bin/sh
# checks out file from SPIDER rcs, places it in current directory, starts edit 
#  -e is do not want a file extension appended


set -- `getopt "e" "$@"` || 
           {
           echo "Usage: `basename $0` [-e] [files]" 1>&2
           exit 1
           }

   shift  # REMOVE TRAILING --

while :
    do
      case "$1" in
         *.*)  # has extension in file-name
               if co -l -f RCS/$1,v
               then
                  chmod ug+w $1
                  chmod +r   $1
                  /usr/local/bin/jot $1
                fi;;
           *)  break ;;
       esac
       shift
    done
    echo "done"
