#!/bin/sh

# Script to convert a file of gnuplot commands (gnufile) to gif format.
#
# make this file executable with the chmod command:
#
#        chmod 775 gnu2gif
#
# then use:  gnu2gif gnufile

# default size is 640 x 480 = size 1.0,1.0
# see 
# gnuplot> help set terminal pbm
# for other options (font size, color, etc)

echo "set size 0.75,0.75"         >  tmpgnupbm
echo "set terminal pbm color"     >> tmpgnupbm
echo "set output 'tmp45tgr6.pbm'" >> tmpgnupbm

gnuplot 'tmpgnupbm' $1

imgcopy 'tmp45tgr6.pbm' $1.gif

\rm 'tmpgnupbm'

\rm 'tmp45tgr6.pbm'
