#! /bin/sh
#  replaces file in RCS, saves reference copy  
#  -e is do not want a file extension appended

set -- `getopt "e" "$@"` || 
           {
           echo "Usage: `basename $0` [-e] [files]" 1>&2
           exit 1
           }
aflag=0
while :
   do
      case "$1" in
         -e) aflag=1 ;;

         --) break ;;  
      esac
      shift
   done

   shift  # REMOVE TRAILING --

while :
   do
      case "$1" in

         *.*)  # has extension in file-name
               if ci  ./$1  RCS/$1,v
               then
                  co -u RCS/$1,v  $1
                  chmod ug+w $1
                  chmod +r   $1
               fi;;

          ?*)  # no extension in filename, default to .html if not -e
               if [ "$aflag" = 1 ]
               then
                 # do not want extension
                 if  ci  ./$1  RCS/$1,v
                 then
                    co -u RCS/$1,v  $1
                    chmod +xr   $1
                    chmod ug+w $1
                 fi
               else         
                  if  ci  ./$1.html  RCS/$1.html,v
                  then
                     co -u RCS/$1.html,v  $1.html
                     chmod ug+w $1.html
                     chmod +r   $1.html
                  fi
               fi;;

           *)  break ;;
         esac
       shift
    done
    echo "done"
