#! /bin/sh
# checks out file from SPIDER rcs, places it in current directory, starts edit 
#  -e is do not want a file extension appended

set -- `getopt "e" "$@"` || 
           {
           echo "Usage: `basename $0` [-e] [files]" 1>&2
           exit 1
           }
aflag=0
while :
   do
      case "$1" in
         -e) aflag=1 ;;

         --) break ;;  
      esac
      shift
   done

   shift  # REMOVE TRAILING --

while :
   do
      case "$1" in

         *.*)  # has extension in file-name
               if co -l -f RCS/$1,v
               then
                  chmod ug+w $1
                  chmod +r   $1
                   /usr/local/bin/jot $1
               fi;;

          ?*)  # no extension in filename, default to .html if not -e
               if [ "$aflag" = 1 ]
               then
                 # do not want extension
                 if  co -l -f RCS/$1,v
                 then
                    chmod ug+w $1
                    chmod +xr  $1
                    /usr/local/bin/jot $1
                  fi


               else 
                  # want to add extension        
                  if co -l -f RCS/$1.html,v
                  then
                     chmod ug+w $1.html
                     chmod +r  $1.html
                      /usr/local/bin/jot $1.html
                  fi
               fi;;


           *)  break ;;
         esac
       shift
    done
