#! /bin/sh
# PURPOSE: Checks out file from  RCS, places it in current directory, starts edit 

      if co -l -f RCS/$1,v
         then
         chmod ug+w $1
         chmod +r   $1
         nedit $1 &
      fi
