#! /bin/sh
# checks out file from  RCS, places it in current directory, starts edit 

      if co -l -f RCS/$1,v
         then
            chmod ug+w $1
            chmod +r   $1
            jot $1
         fi;
