#!/bin/sh
# Shell script to execute commands on multiple nodes
# Do "export NODES=<path to file with nodenames>" to use 
# file other than /etc/nodes

if [ "$1" == "" ]
then
   echo "Usage:"
   echo "$0 <command>"
   exit
fi 

if [ "$NODES" != "" ]
then
   Nodes=$NODES
else
   Nodes=/etc/nodes
fi 

Nodelist=`cat $Nodes`

for node in $Nodelist
  do
    rsh $node $* 
  done
