#! /bin/sh
#  replaces file in  RCS


set -- `getopt "e" "$@"` || 
           {
           echo "Usage: `basename $0`  [files]" 1>&2
           exit 1
           }
aflag=0
while :
   do
      case "$1" in
         -e) aflag=1 ;;

         --) break ;;  
      esac
      shift
   done

   shift  # REMOVE TRAILING --

while :
   do
      case "$1" in

         *.*)  # has extension in file-name
               if ci  ./$1  RCS/$1,v
               then
                  co -u RCS/$1,v  $1
                  chmod ug+w $1
               fi;;

           *)  break ;;
         esac
       shift
    done
    echo "done"
