#! /bin/sh 
#
# SOURCE:       spider/src/makeall
#
# PURPOSE:      Makes all current executables   (not current in 2025!!!)   
#
# SAMPLE USAGE: makeall all (to create all current executables)
#               makeall new (to update all current executables version)

TARGET="$1"
#echo TARGET: $TARGET

DEST="DEST=_tmp"

UNAME=`uname`
#echo UNAME: $UNAME
UNAMEm=`uname -m`
#echo UNAMEm: $UNAMEm
UNAMEn=`uname -n`
#echo UNAMEn: $UNAMEn

PGIVERSIONS=" linux_mp_opt64  linux_mp_intel " 
INTELVERSIONS=" linux_mp_intel64 "
 
ALLVERSIONS="$PGIVERSIONS $INTELVERSIONS" 
#echo ALLVERSIONS: $ALLVERSIONS


case "$TARGET" in

   new) # Update all VERSIONS to Next highest version number

        for SELECT in $ALLVERSIONS
        do
           #echo SELECT: $SELECT
           FILE=../bin/spider_$SELECT"_tmp"
           if [ -e $FILE ] 
           then
              echo "Creating: `./Nextversion ../bin/spider_$SELECT`"
              cp $FILE ../bin/`./Nextversion ../bin/spider_$SELECT`
           else
              echo No: $FILE
           fi
        done
        exit ;;


   *) # Create all VERSIONS 

        if [ "$UNAMEn" = "gyan" ]
           then            # Use Intel compiler
           echo  On: $INTELVERSIONS
     
           for SELECT in $INTELVERSIONS
           do
             echo Running: make -f Makefile_$SELECT.ifort $DEST
             make -f Makefile_$SELECT.ifort $DEST
             echo " "
           done

        else
           #                 Use PGI compiler
           for SELECT in $PGIVERSIONS
           do
             echo Running: make -f Makefile_$SELECT $DEST
             make -f Makefile_$SELECT $DEST
             echo " "
           done
        fi
        exit ;;

esac

exit






