#! /bin/sh
# PURPOSE: Returns incremented SPIDER version executable based on
#          content of CVERS/'VERSION line in file: spider.f
#
# SOURCE:   /usr8/spider/src/Nextversion
# USAGE:    Nextversion spider_linux_mp    
# RETURNS:  spider_linux_mp.??.??.? 
#
# NOTE: find . -name "test.[0-9][0-9].*" -prune does not work for exit status!
 
SPIVERNUM=`(grep -i "CVERS/'VERSION:" spider.f | cut -d " " -f13)`

if ls $1.[0-9][0-9].* 1>/dev/null 2>/dev/null
then
#  List, sort numerically after 3rd dot(../bin..) , use last line only
   LASTFI=`(\ls -1 $1.[0-9][0-9].* | sort -t. +3n -6 | tail -1 )`
 
   INCVAL=`(basename $LASTFI | cut -d"." -f4)`
   EXVERNUM=`(basename $LASTFI | cut -d"." -f2-3)` 
    
   if [ "$EXVERNUM" = "$SPIVERNUM" ]
   then
      echo $1"."$EXVERNUM"."`expr $INCVAL + 1`
   else
      echo $1"."$SPIVERNUM".0"  
   fi
else
   echo  $1"."$SPIVERNUM".0"  
fi

exit 0

