#! /bin/sh
#  replaces file in  RCS, saves reference copy in . 

#shift  # remove trailing --

while :
   do
      if ci  ./$1  
         then
            co -u   $1
            chmod ug+w $1
            chmod +r   $1
      fi;
      shift
   done
